# This is a basic workflow to help you get started with Actions

name: Sync to gitee

# Controls when the action will run. 
on: [ push, pull_request, create ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  git-mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: wearerequired/git-mirror-action@v1
        env:
            # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
            SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
            # 注意替换为你的 GitHub 源仓库地址
            source-repo: "git@github.com:flee-lether/shortcut_badge_plugin.git"
            # 注意替换为你的 Gitee 目标仓库地址
            destination-repo: "git@gitee.com:endcandle/flutter_shortcut_badge.git"
